<?php

declare(strict_types=1);

namespace MLflow\Enum;

/**
 * MLflow Webhook Event Types
 */
enum WebhookEvent: string
{
    // Model Registry Events
    case MODEL_REGISTERED = 'MODEL_REGISTERED';
    case MODEL_VERSION_CREATED = 'MODEL_VERSION_CREATED';
    case MODEL_VERSION_TRANSITIONED_STAGE = 'MODEL_VERSION_TRANSITIONED_STAGE';
    case MODEL_VERSION_TAG_SET = 'MODEL_VERSION_TAG_SET';
    case REGISTERED_MODEL_TAG_SET = 'REGISTERED_MODEL_TAG_SET';
    case REGISTERED_MODEL_ALIAS_SET = 'REGISTERED_MODEL_ALIAS_SET';
    case REGISTERED_MODEL_ALIAS_DELETED = 'REGISTERED_MODEL_ALIAS_DELETED';

    // Prompt Registry Events (if supported)
    case PROMPT_CREATED = 'PROMPT_CREATED';
    case PROMPT_VERSION_CREATED = 'PROMPT_VERSION_CREATED';
    case PROMPT_VERSION_TAG_SET = 'PROMPT_VERSION_TAG_SET';
    case PROMPT_TAG_SET = 'PROMPT_TAG_SET';
    case PROMPT_ALIAS_SET = 'PROMPT_ALIAS_SET';
    case PROMPT_ALIAS_DELETED = 'PROMPT_ALIAS_DELETED';
}
